### PR TITLE
Eslint fixes

### PR DESCRIPTION
**Pull request by kobvel**
General amount of errors reduced to 68.
Some parts which I did not touch yet: 

- console logs (great amount, by Airbnb, should be removed)
- dynamic requires (the same situation)
- some shadow declarations

Rest things are fixed

### CODE REVIEW

**Comment by jonknapp** [comment]
Excellent work @kobvel. I was planning on poking around your commit this evening to make any eslint rule changes that are needed since all of the js files are not ran with the same environment that the default rule set for airbnb expects.

Thanks a lot!  I'll be adding commits to your branch and will pull it in when ready.

**Comment by jonknapp** [comment]
@kobvel could you please remove the `npm-debug.log` file from your commit?

You can run the following to rewrite history so it doesn't sneak in:

```
rm npm-debug.log
git add .
git commit --amend --no-edit
git push origin eslint --force
```

You may have to create a new pull request, but I believe Github is smart enough to figure it out.

**Comment by jonknapp** [comment]
I was able to get the rest of the linting errors taken care of and I'll cherry-pick my commit once we get the `npm-debug.log` file removed. That should give you points for the pull request.

Thank you so much for helping out the project! 👍

**Comment by kobvel** [comment]
Now, should be fine. Deleted debug log!

**Pull request merged**
